name: Build Lean Touch

on: [push, workflow_dispatch]
concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-windows:
    runs-on: [self-hosted, Windows, product]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Build Lean Touch
        shell: bash
        run: |
          export ALTSERVER_PORT=13000
          export ALTSERVER_HOST="192.168.11.35"
          "$UNITY_2021_3_HOME" -batchmode -stackTraceLogType None -projectPath $GITHUB_WORKSPACE/LeanTouch -executeMethod BuildLeanTouch.WindowsBuildFromCommandLine -logFile buildWindows.log -quit

      - uses: actions/upload-artifact@v4
        if: always() # run this step even if one of the previous steps failed
        with:
          name: BuildWindowsArtifact
          path: |
            **/LeanTouchBuild/*
            **/*.log

  build-macOS:
    runs-on: [self-hosted, MAC37]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Build Lean Touch
        run: |
          export ALTSERVER_PORT=13000
          export ALTSERVER_HOST="192.168.11.35"
          echo $CI_PROJECT_DIR
          $UNITY_2021_3_HOME -batchmode -stackTraceLogType None -projectPath $CI_PROJECT_DIR/LeanTouch -executeMethod BuildLeanTouch.MacBuildFromCommandLine -logFile buildMac.log -quit

      - uses: actions/upload-artifact@v4
        if: always() # run this step even if one of the previous steps failed
        with:
          name: BuildMacArtifact
          path: |
            **/LeanTouch.app
            **/*.log

  build-android:
    runs-on: [self-hosted, MAC37]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Build Lean Touch
        run: |
          export ALTSERVER_PORT=13000
          export ALTSERVER_HOST="192.168.11.35"
          $UNITY_2021_3_HOME -batchmode -stackTraceLogType None -projectPath $CI_PROJECT_DIR/LeanTouch -executeMethod BuildLeanTouch.AndroidBuildFromCommandLine -logFile buildAndroid.log -quit

      - uses: actions/upload-artifact@v4
        if: always() # run this step even if one of the previous steps failed
        with:
          name: BuildAndroidArtifact
          path: |
            **/LeanTouch.apk
            **/*.log

  build-iOS:
    runs-on: [self-hosted, MAC37]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Build Lean Touch
        run: |
          export ALTSERVER_PORT=13000
          export ALTSERVER_HOST="192.168.11.35"
          $UNITY_2021_3_HOME -batchmode -stackTraceLogType None -projectPath $CI_PROJECT_DIR/LeanTouch -executeMethod BuildLeanTouch.IosBuildFromCommandLine -logFile buildiOS.log -quit

      - uses: actions/upload-artifact@v4
        if: always() # run this step even if one of the previous steps failed
        with:
          name: BuildiOSArtifact
          path: |
            **/LeanTouch
            **/*.log

  build-WebGL:
    runs-on: [self-hosted, MAC37]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Build Lean Touch
        run: |
          export ALTSERVER_PORT=13000
          export ALTSERVER_HOST="192.168.11.35"
          $UNITY_2021_3_HOME -batchmode -stackTraceLogType None -projectPath $CI_PROJECT_DIR/LeanTouch -executeMethod BuildLeanTouch.WebGLBuildFromCommandLine -logFile buildWebGL.log -quit

      - uses: actions/upload-artifact@v4
        if: always() # run this step even if one of the previous steps failed
        with:
          name: BuildWebGLArtifact
          path: |
            **/build/webgl
            **/*.log